update build requirements for the epel7
error with git 1.8.3
```
+ go mod vendor
go: cloud.google.com/go/firestore@v1.5.0 requires
	google.golang.org/grpc@v1.35.0 requires
	google.golang.org/genproto@v0.0.0-20200526211855-cb27e3aa2013 requires
	google.golang.org/protobuf@v1.23.1-0.20200526195155-81db48ad09cc: invalid version: git fetch --unshallow -f origin in /builddir/go/pkg/mod/cache/vcs/a6c5d6b8734f41936247415390043c979295646fadef73c39eedc1735cd0fef4: exit status 128:
	fatal: git fetch-pack: expected shallow list
error: Bad exit status from /var/tmp/rpm-tmp.QqLnZr (%build)
```